#!/usr/bin/env bash
#
# Deterministically generates the 9 ChatGPT Custom GPT Knowledge bundles
# under chatgpt/knowledge/ from an explicit allowlist of canonical
# repository sources. See chatgpt/knowledge-manifest.md for the full
# bundle-to-source mapping and rationale.
#
# Never edit a file under chatgpt/knowledge/ directly — rebuild it here.
#
# Works when invoked from inside or outside the repository root, since all
# paths are resolved relative to this script's own location.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd -P)"

KNOWLEDGE_DIR="${REPO_ROOT}/chatgpt/knowledge"

fail() {
  echo "error: $1" >&2
  exit 1
}

GENERATED_NOTICE='<!--
Generated from canonical Interview Journey repository sources.
Do not edit this file manually.
Rebuild it using the ChatGPT Knowledge build script
(scripts/build-chatgpt-knowledge.sh or .ps1).
-->'

# Explicit bundle -> source allowlist. One "bundle:source1,source2,..." entry
# per generated file, in generation order. Source paths are repo-root-relative.
BUNDLES=(
  "01-product-orchestration-and-state.md:core/product-definition.md,core/terminology.md,core/scope-and-non-goals.md,core/workflow.md,core/orchestration-policy.md,core/state-management.md,frameworks/15-interview-journey-intelligence-framework.md"
  "02-role-resume-stage-and-fit.md:frameworks/01-role-intelligence-framework.md,frameworks/02-resume-intelligence-framework.md,frameworks/03-interview-stage-framework.md,frameworks/04-role-fit-gap-analysis-framework.md"
  "03-interview-intelligence-and-strategy.md:frameworks/05-interview-intelligence-framework.md,frameworks/06-preparation-strategy-framework.md"
  "04-question-prediction-and-hypotheses.md:frameworks/07-question-prediction-framework.md,frameworks/08-interview-hypothesis-framework.md"
  "05-coding-interviews.md:frameworks/09-coding-interview-decision-engine.md"
  "06-system-design-interviews.md:frameworks/10-system-design-framework.md"
  "07-behavioral-and-answer-coaching.md:frameworks/11-behavioral-interview-framework.md,frameworks/13-answer-coaching-framework.md"
  "08-mock-interviews-and-debrief.md:frameworks/12-mock-interview-framework.md,frameworks/14-post-interview-debrief-framework.md"
  "09-output-contracts-and-quality.md:core/evidence-policy.md,core/accuracy-policy.md,core/context-priority.md,core/quality-gates.md,core/output-contracts.md"
)

# Validate every canonical source exists before generating anything.
for entry in "${BUNDLES[@]}"; do
  sources="${entry#*:}"
  IFS=',' read -ra SRC_LIST <<< "${sources}"
  for src in "${SRC_LIST[@]}"; do
    [ -f "${REPO_ROOT}/${src}" ] || fail "required canonical source not found: ${REPO_ROOT}/${src}"
  done
done

mkdir -p -- "${KNOWLEDGE_DIR}"

# Remove stale generated files not on the current allowlist.
ALLOWED_NAMES=()
for entry in "${BUNDLES[@]}"; do
  ALLOWED_NAMES+=("${entry%%:*}")
done
if [ -d "${KNOWLEDGE_DIR}" ]; then
  while IFS= read -r -d '' existing; do
    name="$(basename -- "${existing}")"
    keep=0
    for allowed in "${ALLOWED_NAMES[@]}"; do
      [ "${name}" = "${allowed}" ] && keep=1 && break
    done
    if [ "${keep}" -eq 0 ]; then
      rm -f -- "${existing}"
    fi
  done < <(find "${KNOWLEDGE_DIR}" -maxdepth 1 -type f -name '*.md' -print0)
fi

# Generate each bundle deterministically.
for entry in "${BUNDLES[@]}"; do
  bundle_name="${entry%%:*}"
  sources="${entry#*:}"
  IFS=',' read -ra SRC_LIST <<< "${sources}"
  out_path="${KNOWLEDGE_DIR}/${bundle_name}"
  tmp_path="${out_path}.tmp"
  src_count="${#SRC_LIST[@]}"

  {
    printf '%s\n\n' "${GENERATED_NOTICE}"
    printf '# %s\n\n' "${bundle_name%.md}"
    idx=0
    for src in "${SRC_LIST[@]}"; do
      idx=$((idx + 1))
      printf '## Source: `%s`\n\n' "${src}"
      # Preserve source content without silent rewriting; normalize CRLF to LF.
      sed 's/\r$//' "${REPO_ROOT}/${src}"
      if [ "${idx}" -lt "${src_count}" ]; then
        printf '\n\n---\n\n'
      else
        printf '\n'
      fi
    done
  } > "${tmp_path}"

  mv -- "${tmp_path}" "${out_path}"
done

echo "Generated ChatGPT Knowledge bundles in: ${KNOWLEDGE_DIR}"
echo ""
echo "Generated files:"
for name in "${ALLOWED_NAMES[@]}"; do
  echo "chatgpt/knowledge/${name}"
done
