<#
.SYNOPSIS
    Deterministically generates the 10 ChatGPT Custom GPT Knowledge bundles
    under chatgpt/knowledge/ from an explicit allowlist of canonical
    repository sources. See chatgpt/knowledge-manifest.md for the full
    bundle-to-source mapping.

.DESCRIPTION
    Never edit a file under chatgpt/knowledge/ directly — rebuild it here.
    Works when invoked from inside or outside the repository root; all paths
    resolve relative to $PSScriptRoot.
#>

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail {
    param([string]$Message)
    Write-Error "error: $Message"
    exit 1
}

$RepoRoot = Split-Path -Parent $PSScriptRoot
$KnowledgeDir = Join-Path $RepoRoot "chatgpt\knowledge"

$GeneratedNotice = @"
<!--
Generated from canonical Interview Journey repository sources.
Do not edit this file manually.
Rebuild it using the ChatGPT Knowledge build script
(scripts/build-chatgpt-knowledge.sh or .ps1).
-->
"@

$Bundles = [ordered]@{
    "01-product-orchestration-and-state.md" = @("core/product-definition.md","core/terminology.md","core/scope-and-non-goals.md","core/workflow.md","core/orchestration-policy.md","core/state-management.md","frameworks/15-interview-journey-intelligence-framework.md")
    "02-role-intelligence.md" = @("frameworks/01-role-intelligence-framework.md")
    "03-resume-stage-and-fit.md" = @("frameworks/02-resume-intelligence-framework.md","frameworks/03-interview-stage-framework.md","frameworks/04-role-fit-gap-analysis-framework.md")
    "04-interview-intelligence-and-strategy.md" = @("frameworks/05-interview-intelligence-framework.md","frameworks/06-preparation-strategy-framework.md")
    "05-question-prediction-and-hypotheses.md" = @("frameworks/07-question-prediction-framework.md","frameworks/08-interview-hypothesis-framework.md")
    "06-coding-interviews.md" = @("frameworks/09-coding-interview-decision-engine.md")
    "07-system-design-interviews.md" = @("frameworks/10-system-design-framework.md")
    "08-behavioral-and-answer-coaching.md" = @("frameworks/11-behavioral-interview-framework.md","frameworks/13-answer-coaching-framework.md")
    "09-mock-interviews-and-debrief.md" = @("frameworks/12-mock-interview-framework.md","frameworks/14-post-interview-debrief-framework.md")
    "10-output-contracts-and-quality.md" = @("core/evidence-policy.md","core/accuracy-policy.md","core/context-priority.md","core/quality-gates.md","core/output-contracts.md")
}

foreach ($bundle in $Bundles.Keys) {
    foreach ($src in $Bundles[$bundle]) {
        $p = Join-Path $RepoRoot $src
        if (-not (Test-Path -LiteralPath $p -PathType Leaf)) { Fail "required canonical source not found: $p" }
    }
}

if (-not (Test-Path -LiteralPath $KnowledgeDir)) {
    New-Item -ItemType Directory -Path $KnowledgeDir -Force | Out-Null
}

$AllowedNames = $Bundles.Keys
Get-ChildItem -LiteralPath $KnowledgeDir -Filter "*.md" -File -ErrorAction SilentlyContinue |
    Where-Object { $AllowedNames -notcontains $_.Name } |
    Remove-Item -Force

foreach ($bundleName in $Bundles.Keys) {
    $sources = $Bundles[$bundleName]
    $outPath = Join-Path $KnowledgeDir $bundleName
    $tmpPath = "$outPath.tmp"

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add($GeneratedNotice)
    $lines.Add("")
    $lines.Add("# " + ($bundleName -replace '\.md$', ''))
    $lines.Add("")

    for ($i = 0; $i -lt $sources.Count; $i++) {
        $src = $sources[$i]
        $lines.Add("## Source: ``$src``")
        $lines.Add("")
        $content = Get-Content -LiteralPath (Join-Path $RepoRoot $src) -Raw
        $content = $content -replace "`r`n", "`n"
        $lines.Add($content.TrimEnd())
        if ($i -lt $sources.Count - 1) {
            $lines.Add("")
            $lines.Add("---")
            $lines.Add("")
        } else {
            $lines.Add("")
        }
    }

    ($lines -join "`n") | Set-Content -LiteralPath $tmpPath -NoNewline
    Move-Item -LiteralPath $tmpPath -Destination $outPath -Force
}

Write-Host "Generated ChatGPT Knowledge bundles in: $KnowledgeDir"
Write-Host ""
Write-Host "Generated files:"
foreach ($name in $Bundles.Keys) {
    Write-Host "chatgpt/knowledge/$name"
}
