<#
.SYNOPSIS
    Deterministically generates the 3 ChatGPT Custom GPT Knowledge bundles
    under chatgpt/knowledge/ from an explicit allowlist of canonical
    repository sources. See chatgpt/knowledge-manifest.md for the full
    bundle-to-source mapping.

.DESCRIPTION
    Each bundle carries a deterministic provenance header (bundle position,
    ordered source list, and a sha256 Content-Digest over the concatenated
    LF-normalized source bytes). The digest depends only on source content,
    so rebuilding from unchanged sources produces byte-identical output.

    Never edit a file under chatgpt/knowledge/ directly - rebuild it here.
    Works when invoked from inside or outside the repository root; all paths
    resolve relative to $PSScriptRoot.

    Logically equivalent to scripts/build-chatgpt-knowledge.sh: same bundle
    names, same source order, same normalized output, same Content-Digest.
#>

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail {
    param([string]$Message)
    Write-Error "error: $Message"
    exit 1
}

$RepoRoot = Split-Path -Parent $PSScriptRoot
$KnowledgeDir = Join-Path $RepoRoot "chatgpt\knowledge"

# Explicit bundle -> source allowlist. Every core/*.md, frameworks/NN-*.md,
# and the two schema/workflow sources appear in exactly one bundle.
$Bundles = [ordered]@{
    "01-product-orchestration-and-quality.md" = @("core/product-definition.md","core/terminology.md","core/scope-and-non-goals.md","core/workflow.md","core/orchestration-policy.md","core/state-management.md","frameworks/15-interview-journey-intelligence-framework.md","core/evidence-policy.md","core/accuracy-policy.md","core/context-priority.md","core/quality-gates.md","core/output-contracts.md")
    "02-role-resume-and-strategy.md" = @("frameworks/01-role-intelligence-framework.md","frameworks/02-resume-intelligence-framework.md","frameworks/03-interview-stage-framework.md","frameworks/04-role-fit-gap-analysis-framework.md","frameworks/05-interview-intelligence-framework.md","frameworks/06-preparation-strategy-framework.md","schemas/public-research-evidence.schema.md","workflows/research-current-interview-intelligence.md","frameworks/07-question-prediction-framework.md","frameworks/08-interview-hypothesis-framework.md")
    "03-interview-execution.md" = @("frameworks/09-coding-interview-decision-engine.md","frameworks/10-system-design-framework.md","frameworks/11-behavioral-interview-framework.md","frameworks/12-mock-interview-framework.md","frameworks/13-answer-coaching-framework.md","frameworks/14-post-interview-debrief-framework.md")
}

$BundleCount = $Bundles.Count

foreach ($bundle in $Bundles.Keys) {
    foreach ($src in $Bundles[$bundle]) {
        $p = Join-Path $RepoRoot $src
        if (-not (Test-Path -LiteralPath $p -PathType Leaf)) { Fail "required canonical source not found: $p" }
    }
}

if (-not (Test-Path -LiteralPath $KnowledgeDir)) {
    New-Item -ItemType Directory -Path $KnowledgeDir -Force | Out-Null
}

$AllowedNames = $Bundles.Keys
Get-ChildItem -LiteralPath $KnowledgeDir -Filter "*.md" -File -ErrorAction SilentlyContinue |
    Where-Object { $AllowedNames -notcontains $_.Name } |
    Remove-Item -Force

# Read a source file and normalize CRLF -> LF (mirrors `sed 's/\r$//'`).
function Read-NormalizedSource {
    param([string]$RelPath)
    $raw = Get-Content -LiteralPath (Join-Path $RepoRoot $RelPath) -Raw
    return ($raw -replace "`r`n", "`n") -replace "`r", ""
}

$sha256 = [System.Security.Cryptography.SHA256]::Create()
$utf8 = New-Object System.Text.UTF8Encoding($false)

$bundleIndex = 0
foreach ($bundleName in $Bundles.Keys) {
    $bundleIndex++
    $sources = $Bundles[$bundleName]
    $outPath = Join-Path $KnowledgeDir $bundleName
    $tmpPath = "$outPath.tmp"

    # Content-Digest: sha256 over concatenated LF-normalized source bytes,
    # in listed order. Deterministic from source content only.
    $concat = ($sources | ForEach-Object { Read-NormalizedSource $_ }) -join ""
    $digestBytes = $sha256.ComputeHash($utf8.GetBytes($concat))
    $digest = -join ($digestBytes | ForEach-Object { $_.ToString("x2") })

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("<!--`n")
    [void]$sb.Append("Generated from canonical Interview Journey repository sources.`n")
    [void]$sb.Append("Do not edit this file manually.`n")
    [void]$sb.Append("Rebuild it using the ChatGPT Knowledge build script`n")
    [void]$sb.Append("(scripts/build-chatgpt-knowledge.sh or .ps1).`n")
    [void]$sb.Append("`n")
    [void]$sb.Append("Bundle: $bundleName ($bundleIndex of $BundleCount)`n")
    [void]$sb.Append("Sources (in order):`n")
    foreach ($src in $sources) { [void]$sb.Append("  $src`n") }
    [void]$sb.Append("Content-Digest (sha256 of concatenated LF-normalized sources): $digest`n")
    [void]$sb.Append("-->`n`n")
    [void]$sb.Append("# " + ($bundleName -replace '\.md$', '') + "`n`n")

    for ($i = 0; $i -lt $sources.Count; $i++) {
        $src = $sources[$i]
        [void]$sb.Append("## Source: ``$src```n`n")
        [void]$sb.Append((Read-NormalizedSource $src))
        if ($i -lt $sources.Count - 1) {
            [void]$sb.Append("`n`n---`n`n")
        } else {
            [void]$sb.Append("`n")
        }
    }

    [System.IO.File]::WriteAllText($tmpPath, $sb.ToString(), $utf8)
    Move-Item -LiteralPath $tmpPath -Destination $outPath -Force
}

Write-Host "Generated ChatGPT Knowledge bundles in: $KnowledgeDir"
Write-Host ""
Write-Host "Generated files:"
foreach ($name in $Bundles.Keys) {
    Write-Host "chatgpt/knowledge/$name"
}
